# Generated by Django 4.1.3 on 2023-01-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_door', models.BooleanField()),
                ('reaction', models.CharField(choices=[('p', 'Позитивно'), ('n', 'Нейтрально'), ('b', 'Негативно')], default='n', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('patr', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('to_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('flats', models.IntegerField()),
                ('to_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
    ]
