# Generated by Django 4.1.3 on 2023-01-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='to_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.houses'),
        ),
    ]
