# Generated by Django 4.1.3 on 2023-01-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_check_to_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
